version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG}
    image: devops-app:${IMAGE_TAG}
    ports:
      - "5002:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
