services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG}
    image: devops-app:${IMAGE_TAG}
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"